name: capstone
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  
  - pip:
    - cudatoolkit=11.3.1=h59b6b97_2
    - numpy=1.21.2=py39hfca59bb_0
    - numpy-base=1.21.2=py39h0829f74_0
    - pip=21.2.4=py39haa95532_0
    - python=3.9.7=h6244533_1
    - pytorch=1.10.2=py3.9_cuda11.3_cudnn8_0
    - torchaudio=0.10.2=py39_cu113
    - torchvision=0.11.3=py39_cu113
    - absl-py==1.0.0
    - albumentations==1.1.0
    - altair==4.1.0
    - antlr4-python3-runtime==4.8
    - appdirs==1.4.4
    - argon2-cffi==21.1.0
    - astor==0.8.1
    - attrs==21.2.0
    - backcall==0.2.0
    - base58==2.1.0
    - black==21.4b2
    - bleach==4.1.0
    - blinker==1.4
    - cachetools==4.2.4
    - cffi==1.14.6
    - charset-normalizer==2.0.6
    - click==7.1.2
    - cloudpickle==2.0.0
    - configparser==5.0.2
    - cycler==0.10.0
    - cython==0.29.24
    - debugpy==1.5.0
    - decorator==5.1.0
    - defusedxml==0.7.1
    - detectron2==0.6
    - dict2xml==1.7.1
    - docker-pycreds==0.4.0
    - entrypoints==0.3
    - future==0.18.2
    - fvcore==0.1.5.post20211023
    - gitdb==4.0.7
    - gitpython==3.1.24
    - google-auth==2.3.3
    - google-auth-oauthlib==0.4.6
    - grpcio==1.43.0
    - hydra-core==1.1.1
    - idna==3.2
    - imageio==2.9.0
    - imantics==0.1.12
    - importlib-metadata==4.10.0
    - iopath==0.1.9
    - ipykernel==6.4.1
    - ipython==7.28.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.5
    - jedi==0.18.0
    - jinja2==3.0.2
    - joblib==1.1.0
    - jsonschema==4.0.1
    - jupyter-client==7.0.6
    - jupyter-core==4.8.1
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.2
    - kiwisolver==1.3.2
    - lxml==4.7.1
    - markdown==3.3.6
    - markupsafe==2.0.1
    - matplotlib==3.4.3
    - matplotlib-inline==0.1.3
    - mistune==0.8.4
    - mypy-extensions==0.4.3
    - nbclient==0.5.4
    - nbconvert==6.2.0
    - nbformat==5.1.3
    - nest-asyncio==1.5.1
    - networkx==2.6.3
    - notebook==6.4.4
    - oauthlib==3.1.1
    - omegaconf==2.1.1
    - opencv-python==4.5.5.64
    - opencv-python-headless==4.5.5.62
    - packaging==21.0
    - pandas==1.3.3
    - pandocfilters==1.5.0
    - parso==0.8.2
    - pathspec==0.9.0
    - pathtools==0.1.2
    - pickleshare==0.7.5
    - pillow==8.3.2
    - portalocker==2.3.2
    - prometheus-client==0.11.0
    - promise==2.3
    - prompt-toolkit==3.0.20
    - protobuf==3.18.1
    - psutil==5.8.0
    - pyarrow==5.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycocotools==2.0.2
    - pycparser==2.20
    - pydeck==0.7.0
    - pydot==1.4.2
    - pygments==2.10.0
    - pympler==0.9
    - pyparsing==2.4.7
    - pyrsistent==0.18.0
    - python-dateutil==2.8.2
    - pytz==2021.3
    - pywavelets==1.1.1
    - pywin32==301
    - pywinpty==1.1.4
    - pyyaml==5.4.1
    - pyzmq==22.3.0
    - qudida==0.0.4
    - regex==2021.11.10
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - rsa==4.8
    - scikit-image==0.18.3
    - scikit-learn==1.0
    - scipy==1.7.1
    - semver==2.13.0
    - send2trash==1.8.0
    - sentry-sdk==1.4.3
    - shortuuid==1.0.1
    - smmap==4.0.0
    - streamlit==1.7.0
    - subprocess32==3.5.4
    - tabulate==0.8.9
    - tensorboard==2.7.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - termcolor==1.1.0
    - terminado==0.12.1
    - testpath==0.5.0
    - threadpoolctl==3.0.0
    - tifffile==2021.8.30
    - toolz==0.11.1
    - tornado==6.1
    - tqdm==4.62.3
    - traitlets==5.1.0
    - tzdata==2021.2.post0
    - tzlocal==3.0
    - urllib3==1.26.7
    - validators==0.18.2
    - wandb==0.12.4
    - watchdog==2.1.6
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - werkzeug==2.0.2
    - widgetsnbextension==3.5.1
    - xmljson==0.2.1
    - yacs==0.1.8
    - yaspin==2.1.0
    - zipp==3.7.0
prefix: C:\Users\Julia Rosenrauch\anaconda3\envs\capstone
